apiVersion: v1
kind: Pod
metadata:
  name: mysite
  labels:
    function: webserver
spec:
  containers:
  - name: httpd
    image: ghcr.io/scotthill92/cis-92:milestone-4.6
    env:
    - name: SECRET_KEY
      value: "kjdgnfeknfvkdnvfmglevn "
    - name: PORT
      value: "80"
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /polls/
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 30
