apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  containers:
  - name: postgres
    image: docker.io/postgres:14.1
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_PASSWORD
      value: "django"
    - name: POSTGRES_DB
      value: "mysite"
    